export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_TRIPS_SUCCESS = 'LOAD_TRIPS_SUCCESS';
export const SAVE_TRIP_SUCCESS = 'SAVE_TRIP_SUCCESS';
export const UPDATE_TRIP_SUCCESS = 'UPDATE_TRIP_SUCCESS';
export const CREATE_TRIP_SUCCESS = 'CREATE_TRIP_SUCCESS';
export const DELETE_TRIP_SUCCESS = 'DELETE_TRIP_SUCCESS';

export const LOAD_WAYPOINTS_SUCCESS = 'LOAD_WAYPOINTS_SUCCESS';
export const SAVE_WAYPOINT_SUCCESS = 'SAVE_WAYPOINT_SUCCESS';
export const UPDATE_WAYPOINT_SUCCESS = 'UPDATE_WAYPOINT_SUCCESS';
export const CREATE_WAYPOINT_SUCCESS = 'CREATE_WAYPOINT_SUCCESS';
export const DELETE_WAYPOINT_SUCCESS = 'DELETE_WAYPOINT_SUCCESS';
